### ISSUE TITLE
ground truth depth for aerial dataset

### ISSUE THREAD

**Issue by abhishek31704** [paschalidoud/raynet#10]
Hi,

The gt_depth_0.npy for gt folder is missing under the aerial_dataset. Where can I get this?

**Comment by paschalidoud** [comment]
Hi @abhishek31704,

Thank you very much for your interest in our work! You can find the gt depth maps  from

https://drive.google.com/drive/folders/162SiHEfXAOiTd1GrT5uiENsPdldg6rDI?usp=sharing

I am closing this issue for now but feel free to reopen it.

Best,
Despoina
