### ISSUE TITLE
A question about Python version

### ISSUE THREAD

**Issue by wlcosta** [paschalidoud/raynet#2]
I installed RayNet using Python 3.6, but the scripts appear to be using Python 2.x syntax. However, the Tensorflow build for Python 2.x is really outdated, and `pip install raynet` gives an error about this.

Is the syntax wrong or am I missing something?

```
[...] \Python\Python36\lib\site-packages\raynet-0.2-py3.6-win-amd64.egg\raynet\scripts\forward_pass.py", line 14
    print "******PyCUDA is required for the forward pass******"
                                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("******PyCUDA is required for the forward pass******")?
```

**Comment by paschalidoud** [comment]
Hi,

You are right, indeed I am using Python 2.7. In case you would like to port the codebase in Python 3.6 I am morry than happy to support this.

Cheers,
Despoina
