### ISSUE TITLE
json example missing

### ISSUE THREAD

**Issue by miccec** [paschalidoud/raynet#3]
Hi, thanks for this great project!
I would like to rerun the code on the example data. However the documentation refers to a json file for the raynet_pretrain which an example in the config folder. However there is no son file in the config folder. Could you be so kind to share an example of the json file?
Thank you

**Comment by paschalidoud** [comment]
Hi @miccec,

I am really sorry for this. I just pushed bf468da with two example files, one for the aerial dataset and one for the DTU dataset.

I am closing the issue but feel free to reopen it (or a new one) in case of problems. 

Best,
Despoina
